### ISSUE TITLE
Errors in all the Ember quizes

### ISSUE THREAD

**Issue by daphnedeng** [udacity/FEF-Quiz-Ember-Nested-Routes#1]
all quiz files have error. Not able to open any of them.
```
Uncaught TypeError: Cannot read property 'String' of undefined
    at Module.callback (string.js:4)
    at Module.exports (loader.js:83)
    at Module.build (loader.js:133)
    at findModule (loader.js:181)
    at Module.reify (loader.js:115)
    at Module.build (loader.js:133)
    at findModule (loader.js:181)
    at Module.reify (loader.js:115)
    at Module.build (loader.js:133)
    at findModule (loader.js:181)```

**Comment by DagmaraS90** [comment]
Hi! I have the exact same problem! @daphnedeng did you managed to find solution to this?

**Comment by daphnedeng** [comment]
no... Couldn't figure out what's going on. If you find a solution later on
please let me know

**Comment by Abhiek187** [comment]
See [this issue](https://github.com/emberjs/ember-inflector/issues/145)

Basically, I had to insert `"ember-inflector": "2.2.0"` into `package.json` and then run `npm install` twice before the quizzes started working again.

**Comment by sgouver** [comment]
where in package.json did you insert "ember-inflector": "2.2.0", because I receive an additional error...

**Comment by batwell31** [comment]
you put it in "devDependencies" object

**Comment by papanugget** [comment]
The updated package.json with ember-inflector inserted did nothing to the error on my end.  From another thread I had to manually edit string.js in the ember-inflector package from 
`if (Ember.ENV.EXTEND_PROTOTYPES === true || Ember.ENV.EXTEND_PROTOTYPES.String) {`
to 
`if (Ember.ENV.EXTEND_PROTOTYPES === true &&Ember.ENV.EXTEND_PROTOTYPES.String) {`

Hope that helps someone out there.
