### ISSUE TITLE
Not loading Instructions

### ISSUE THREAD

**Issue by DuskyByte** [udacity/FEF-Quiz-Ember-Nested-Routes#4]
After running all the prerequisite commands and then ember server. I open the localhost and it pulls up a blank page with NestedRoutes as the title.

**Comment by hbkwong** [comment]
Hey DuskyByte, I wasn't able to reproduce your error. I suggest making sure you have Ember CLI installed globally, then try again. Feel free to reopen this if you're still running into issues!
